chore: merge two title linting workflows

diff --git a/.github/workflows/pr-title-linting.yaml b/.github/workflows/pr-title-linting.yaml
--- a/.github/workflows/pr-title-linting.yaml
+++ b/.github/workflows/pr-title-linting.yaml
@@ -1,4 +1,4 @@
-name: "Pull request title conventional commit validation"
+name: "Pull request title linting"
 
 permissions:
   contents: read
@@ -14,6 +14,7 @@ on:
 
 jobs:
   pr-title-conventional-commit-validation:
+    name: "Conventional commit validation"
     runs-on: ubuntu-22.04
     env:
       VALID_TYPES: "feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert"
@@ -94,4 +95,75 @@ jobs:
         if: ${{ env.VALIDATION_RESULT == 'failure' }}
         run: |
           echo "Pull request title ($TITLE) is not properly formatted."
+          exit 1
+  pr-title-jira-validation:
+    name: "Jira issues validation"
+    runs-on: ubuntu-22.04
+    env:
+      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      COMMENT_TITLE: "## Jira Pull Request Link"
+      # https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
+      TITLE: ${{ github.event.pull_request.title }}
+      PR_TITLE_SAFE: ${{ github.event.pull_request.title }}
+    steps:
+      - name: Check if title contains Jira issue keys
+        run: |
+          PR_TITLE="$TITLE"
+          if [[ "$PR_TITLE" =~ \[(#?[A-Z]*-[0-9]*,?){1,}\] ]]; then
+            echo "PR title is valid."
+            echo "VALIDATION_RESULT=success" >> $GITHUB_ENV
+          else
+            echo "PR title is invalid."
+            echo "VALIDATION_RESULT=failure" >> $GITHUB_ENV
+          fi
+
+      - name: Find existing Jira comment
+        run: |
+          EXISTING_COMMENT=$(gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
+            --jq ".[] | select(.body | startswith(\"$COMMENT_TITLE\")) | .id")          
+          COMMENT_COUNT=$(echo "$EXISTING_COMMENT" | wc -l)
+          if [ "$COMMENT_COUNT" -gt 1 ]; then
+            echo "Multiple comments found with the same title. Please review the comments."
+            exit 2
+          else
+            echo "EXISTING_COMMENT_ID=$EXISTING_COMMENT" >> $GITHUB_ENV
+          fi
+
+      - name: Create or update Jira link comment
+        run: |
+          if [[ "${{ env.VALIDATION_RESULT }}" == "success" ]]; then
+            PR_TITLE="$TITLE"
+            ISSUES_STR=$(awk -F'\\[|\\]' '{print $2}' <<< "$PR_TITLE" | sed "s/#//g")
+            IFS=',' read -ra ISSUES <<< "$ISSUES_STR"
+            JIRA_COMMENT_MARKDOWN="$COMMENT_TITLE"$'\n\n'
+            JIRA_COMMENT_MARKDOWN+="This Pull Request refers to Jira issues:"$'\n'
+
+            for ISSUE in "${ISSUES[@]}"; do
+              ISSUE=$(echo "$ISSUE" | sed 's/^ *//;s/ *$//') # Trim spaces
+              JIRA_COMMENT_MARKDOWN+="- [$ISSUE](https://pagopa.atlassian.net/browse/$ISSUE)"$'\n'
+            done
+
+            echo "Gira comment markdown: $JIRA_COMMENT_MARKDOWN"          
+            COMMENT_BODY=$JIRA_COMMENT_MARKDOWN
+          else 
+            COMMENT_BODY="${{ env.COMMENT_TITLE }}"$'\n\n'
+            COMMENT_BODY+=":x: The PR title is wrongly formatted."$'\n'
+            COMMENT_BODY+="Example -> chore: [TICKET] your title"
+          fi
+
+          echo "Comment body: $COMMENT_BODY"
+
+          if [[ -n "${{ env.EXISTING_COMMENT_ID }}" ]]; then
+            echo Update existing comment
+            gh api repos/${{ github.repository }}/issues/comments/${{ env.EXISTING_COMMENT_ID }} \
+              -X PATCH -F body="$COMMENT_BODY"
+          else
+            gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
+              -X POST -F body="$COMMENT_BODY"
+          fi
+
+      - name: Failure message
+        if: env.VALIDATION_RESULT != 'success'
+        run: |
+          echo "Pull request title ($PR_TITLE_SAFE) is not properly formatted or it is not related to any Jira issue"
           exit 1
